Redis repos
nunchuck/personService pull request #8
Opened 2017-05-04 15:26 UTC by nunchuck

Completed the customer save and find behaviour tests, next will be writing the behat tests for gym owner and meals.
Changed the unique identifier to email and refactored the code accordingly.
Figured out that travis needs to know to install redis-server as a service...eventually.
Would be greatful if someone could take a look at the code and give me any pointers on where it could be improved or refactored down to more efficient :D
@mannion007 @braddle

2017-05-07 20:19 UTC, mannion007 requested changes
Good progress, I have added some feedback for you to look into and consider but I am impressed with what you have achieved.

2017-05-07 20:19 UTC, mannion007 commented on src/Infrastructure/RedisCustomerRepository.php
> +    public function signedUp(Customer $email)
This function was not part of the interface we designed. It does the same thing as the save function - why do you need to add this?

2017-05-07 20:19 UTC, mannion007 commented on composer.json
> +        "phpunit/phpunit": "^6.1"
Doesn't look like you are using PHPUnit yet - I'd remove it for now. (You can use it if you want, although you could get by just fine with just PHP spec for this project)

2017-05-07 20:19 UTC, mannion007 commented on .gitignore
> +dump.rdb
What are these?

2017-05-07 20:19 UTC, mannion007 commented on .gitignore
> +test.php
What are these?

2017-05-07 20:19 UTC, mannion007 commented on features/redisCustomer.feature
> +Feature: Saving and finding a customer
This feature file reads more like a unit test than a behavioural test. Remember that these scenarios are intended to be something you can discuss with the business owner and have them understand and contribute to.

Putting things in the database and getting them back out are purely technical concerns. The business owner will not understand or have any input into how this works, so there is no point in showing it to them.

Of course, this stuff does need to be tested, but Behat is not the correct tool to test your Redis Repository. You should instead use PHP Spec or PHP Unit to unit test the Redis Customer Repository.

2017-05-08 14:43 UTC, nunchuck commented on src/Infrastructure/RedisCustomerRepository.php
> +    public function signedUp(Customer $email)
I have removed it. I got a little bit confused last week so am going to implement the feedback you've given cheers.

2017-05-08 14:44 UTC, nunchuck commented on .gitignore
> +dump.rdb
I think this is something redis related, as it only appeared when I started using Redis

2017-05-08 14:54 UTC, nunchuck commented on composer.json
> +        "phpunit/phpunit": "^6.1"
Removed until it becomes necessary

2017-05-08 14:55 UTC, nunchuck commented on .gitignore
> +dump.rdb
Yeah, it is for Redis so just ignoring it until i figure out exactly how it's used

2017-05-08 14:55 UTC, nunchuck commented on .gitignore
> +test.php
This was a test I made to check my redis functions, it has now been removed.

2017-05-08 15:04 UTC, merged